---
resources:
- name: resource-tutorial
  type: git
  source:
    uri: https://github.com/gthomson31/helloconcourse.git
    branch: master
        
- name: my-timer
  type: time
  source:
    interval: 2m

jobs:
- name: job-create-dir-files-then-delete
  public: true
  plan:
  - get: resource-tutorial
  - get: my-timer
  - trigger: true
  - task: create-dir-files-then-delete
    file: resource-tutorial/script/files/create_make_del.yml
