---
resources:
- name: resource-tutorial
  type: git
  source:
    uri: https://github.com/gthomson31/helloconcourse.git
    branch: master

jobs:
- name: job-create-dir-files-then-delete
  public: true
  plan:
  - aggregate:
    - get: resource-tutorial
  - task: create-dir-files-then-delete
    file: files/create_make_del.yml
